// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Persistence;

namespace Persistence.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.14");

            modelBuilder.Entity("Domain.Channel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Channels");

                    b.HasData(
                        new
                        {
                            Id = new Guid("c2b70f80-9b85-4c19-9a79-8dcd29bc33de"),
                            Description = "Canal dedicado a dotnet core",
                            Name = "DotNetCore"
                        },
                        new
                        {
                            Id = new Guid("ebc135ae-9b2c-45c7-afe2-d4681f21591e"),
                            Description = "Canal dedicado a dotnet react js",
                            Name = "React JS"
                        },
                        new
                        {
                            Id = new Guid("afa41f50-4def-4442-8541-40b36e879909"),
                            Description = "Canal dedicado a dotnet angular",
                            Name = "Angular"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
